/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as standardTokenSol from "./StandardToken.sol";
export { Greeter__factory } from "./Greeter__factory";
