/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as standardTokenSol from "./StandardToken.sol";

export type { standardTokenSol };
export type { Greeter } from "./Greeter";
export * as factories from "./factories";
export { Greeter__factory } from "./factories/Greeter__factory";
export type { ERC20Token } from "./StandardToken.sol/ERC20Token";
export { ERC20Token__factory } from "./factories/StandardToken.sol/ERC20Token__factory";
export type { StandardToken } from "./StandardToken.sol/StandardToken";
export { StandardToken__factory } from "./factories/StandardToken.sol/StandardToken__factory";
